### ISSUE TITLE
Medium severity vulnerability found on concat-stream@1.4.10

### ISSUE THREAD

**Issue by Pajk** [substack/static-module#26]
The `concat-stream` version used in `static-module` contains a vulnerability as reported by [Snyk]( https://snyk.io/vuln/npm:concat-stream:20160901). It has been fixed in version `1.5.2`.

**Comment by hubdotcom** [comment]
+1

Uninitialized Memory Exposure

Medium severity
Vulnerable module: concat-stream

Introduced through: static-module@1.3.1 › concat-stream@1.4.10

https://snyk.io/vuln/npm:concat-stream:20160901

**Comment by mattdesl** [comment]
fixed in 1.3.2
